config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  
  get 'signup' => 'users#new', as: 'signup'
  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  get 'register' => 'registrations#create', as: 'register'
  get 'cancel_register' => 'registrations#destroy', as: 'cancel_register'

  resources :users
  resources :sessions
  resources :events
  resources :registrations

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, :starting_date_time, :ending_date_time, :description, :location, presence: true
  validates :title, uniqueness: true
  validate :end_date_is_after_start_date

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'

  has_many :registrations
  has_many :attendees, through: :registrations, source: :user

  scope :past, -> { where('ending_date_time < ?', DateTime.now) }
  scope :upcoming, -> { where('starting_date_time > ?', DateTime.now) }

  private

  def end_date_is_after_start_date
    return if ending_date_time.blank? || starting_date_time.blank?

    errors.add(:ending_date_time, 'cannot be before the start date') if ending_date_time < starting_date_time
  end
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :user_id, uniqueness: { scope: :event_id }
  validates :event_id, uniqueness: { scope: :user_id }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  has_many :registrations
  has_many :attended_events, through: :registrations, source: :event

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def user_signed_in?
    return false if session[:user_id].nil?

    true
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_login, only: [:show]

  def index
    @events = Event.all
    @past_events = Event.past
    @upcoming_events = Event.upcoming
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      flash[:notice] = "Event '#{@event.title}' was successfully created!"
      redirect_to @event
    else
      flash[:alert] = if @event.errors.nil?
                        'Something went wrong, please try again'
                      else
                        @event.errors.messages
                      end
      render 'new'
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :starting_date_time, :ending_date_time, :location)
  end

  # rubocop: disable Style/GuardClause

  def require_login
    unless user_signed_in?
      flash[:alert] = 'You must be logged in to access this'
      redirect_to login_path
    end
  end

  # rubocop: enable Style/GuardClause
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def create
    user = current_user
    event = Event.find(params[:id])

    if event.attendees.include?(user)
      redirect_to event, notice: "You're already attending this event"
    else
      event.attendees << user
      redirect_to event, notice: 'Succesfuly added to attend this event'
    end
  end

  def destroy
    event = Event.find(params[:id])

    event.attendees.delete(current_user)
    redirect_to event, notice: "You're no longer attending this event"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_name(params[:name])
    if user
      session[:user_id] = user.id
      redirect_to root_path, notice: "Welcome back #{user.name}, you are succesfully logged in"
    else
      flash.now.alert = 'User does not exists'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Succesfully logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    session[:user_id] = @user.id
    flash.notice = "User #{@user.name} has succesfully signed in"
    redirect_to root_path
  end

  def show
    @user = User.find(params[:id])
    @created_events = @user.events
    @past_events = @user.attended_events.past
    @upcoming_events = @user.attended_events.upcoming
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with model: event do |f| %>
<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>

<div class="field">
  <%= f.label :starting_datetime %>
  <%= f.date_select :starting_date_time %>
</div>

<div class="field">
  <%= f.label :ending_datetime %>
  <%= f.date_select :ending_date_time %>
</div>

<div class="field">
  <%= f.label :location %>
  <%= f.text_field :location %>
</div>

<div class="field">
  <%= f.label :description %>
  <%= f.text_field :description %>
</div>

<div class="actions">
  <%= f.submit 'Create event' %>
</div>
<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<div class="container-index">
  <h1>Upcoming Events</h1>
  <section class="display-events">
    <% @upcoming_events.each do |event| %>
    <div>
      <h3> <%= link_to event, id:event.title do  %> <%= event.title %> <% end %></h3>
      <p><%= event.description %></p>
      <small><%= event.creator.name %></small>
    </div>
    <% end %>
  </section>
  <h1>Past Events</h1>
  <section class="display-events">
    <% @past_events.each do |event| %>
    <div>
      <h3> <%= link_to event do %> <%= event.title %> <% end %></h3>
      <p><%= event.description %></p>
      <small><%= event.creator.name %></small>
    </div>
    <% end %>
  </section>
</div>

app/views/events/new.html.erb
<div class="container-new">

  <div class="card">

    <%= form_with model: @event do |f| %>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="dates">
      <div class="field-date">
        <%= f.label :starting_datetime %>
        <%= f.datetime_field :starting_date_time %>
      </div>

      <div class="field-date">
        <%= f.label :ending_datetime %>
        <%= f.datetime_field :ending_date_time %>
      </div>
    </div>

    <div class="field">
      <%= f.label :location %>
      <%= f.text_field :location %>
    </div>

    <div class="description field">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>

    <div class="actions">
      <%= f.submit 'Create event' %>
    </div>
    <% end %>

  </div>
</div>

app/views/events/show.html.erb
<div class="container-show">
  <h1><%= @event.title %></h1>
  <div class="event">
    <div class="description">
      <p><%= @event.description %></p>
    </div>
    <div class="info">
      <p><i class="fas fa-user-astronaut"></i> <%= @event.creator.name %></p>
      <p><i class="far fa-calendar-alt"></i> <%= @event.starting_date_time.strftime("%B %-d, %Y at %l:%M %p") %></p>
      <p><i class="far fa-calendar-alt"></i> <%= @event.ending_date_time.strftime("%B %-d, %Y at %l:%M %p") %></p>
      <p><i class="fas fa-map-marked-alt"></i> <%= @event.location %></p>
    </div>

  </div>
  <% unless Event.all.past.include?(@event) %>
  <% if @event.attendees.include?(current_user) %>
  <%= link_to cancel_register_path(id: @event.id) do %> <button type='button' class='cancel'>Cancel Attendance</button> <% end %>
  <% else %>
  <%= link_to register_path(id: @event.id) do %> <button type='button' class='attend'>Attend this event</button> <% end %>
  <% end %>
  <% end %>

</div>
<div class="container-attendance">


  <button type='button' class='collapsible'>View attendance</button>

  <div class="content">
    <% @event.attendees.each do | attendee | %>
    <p> <%= attendee.name %> </p>
    <% end %>
  </div>
  <%= javascript_pack_tag "slide" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Private Events</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag "https://pro.fontawesome.com/releases/v5.10.0/css/all.css" %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script defer src="/your-path-to-fontawesome/js/fontawesome.js"></script>
</head>

<body>
  <div class="container">
    <nav>
      <%= link_to root_path do %> <div>
        <%= image_tag "logo.png" %> <p>Bati-Events</p>
      </div> <% end %>
      <ul>
        <% if user_signed_in? %>

        <li>
          <%= link_to "New event", new_event_path %>
        </li>

        <li>
          <%= link_to current_user.name, user_path(current_user) %>
        </li>
        <li>
          <%= link_to 'Log out', logout_path %>
        </li>

        <% else %>

        <li>
          <%= link_to 'Log in', login_path %>
        </li>
        <li>
          <%= link_to 'Sign up', signup_path %>
        </li>

        <% end %>

      </ul>
    </nav>
  </div>
  <% if flash[:notice] %>
  <div class="notification notice">
    <p><%= notice %></p>
  </div>
  <% end %>
  <% if flash[:alert] %>
  <div class="notification alert">
    <p><%= alert %></p>
  </div>
  <% end %>

  <main class="<%= controller.controller_name%>">
    <%= yield %>
  </main>

</body>

</html>

app/views/users/_form.html.erb
<div class="card">

  <%= form_with model: user do |f| %>
  <div class="field">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>

</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>index</h1>

<p><%= session[:user_id] %></p>

app/views/users/new.html.erb
<div class="container-30">

  <%= image_tag "logo.png" %>

  <h1>Sign up to Bati-events</h1>

  <%= render "form", user: @user %>

  <p>Already have an account log in <%= link_to "here", login_path %></p>

</div>

app/views/users/show.html.erb
<div class="container-80">
  <h1><%= current_user.name %>'s Events Profile</h1>
  <div class="events-container">
    <div>
      <h2>Hosted Events</h2>

      <% @created_events.each do |event| %>

      <p> <%= link_to event do %> <%= event.title %><% end %> </p>
      <% end %>
    </div>
    <div>
      <h2>Upcoming Events</h2>
      <% @upcoming_events.each do |event| %>

      <p> <%= link_to event do %> <%= event.title %><% end %> </p>
      <% end %>
    </div>
    <div>
      <h2>Attended Events</h2>
      <% @past_events.each do |event| %>

      <p> <%= link_to event do %> <%= event.title %><% end %> </p>
      <% end %>
    </div>
  </div>
</div>